export const START_SEARCH_MOVIE = "START_SEARCH_MOVIE";
export const SUCCESS_SEARCH_MOVIE = "SUCCESS_SEARCH_MOVIE";
export const FAIL_SEARCH_MOVIE = "FAIL_SEARCH_MOVIE";

export const START_GET_MOVIES = "START_GET_MOVIES";
export const SUCCESS_GET_MOVIES = "SUCCESS_GET_MOVIES";
export const FAIL_GET_MOVIES = "FAIL_GET_MOVIES";

export const START_GET_MOVIE_BY_ID = "START_GET_MOVIE_BY_ID";
export const SUCCESS_GET_MOVIE_BY_ID = "SUCCESS_GET_MOVIE_BY_ID";
export const FAIL_GET_MOVIE_BY_ID = "FAIL_GET_MOVIE_BY_ID";
